# This is part of a GNU-Makefile, to specify system-dependent 
# parts of the Makefile enviroment.

# This gets included as part of the GNU-Makefile used in each of 
# the subdirectories.

# Waterloo modifications should make picking up the right machine
# definition automatic.  You should not have to edit this file for
# either MIPS machines (cantor.math), or SPARC (descartes, napier,
# cayley, ...).  

ifndef MAKEFILE_DEP
define MAKEFILE_DEP
yes
endef

# These definitions may change as the software is updated.
# Some of them are also system dependent
CPP=/lib/cpp
CC = g++ -m32
LD = g++ -m32
AS = as --32

uname = $(shell uname)

mips_arch = dec-mips-ultrix



# 386, 386BSD Unix, or NetBSD Unix (available via anon ftp 
#    from agate.berkeley.edu)
ifeq ($(uname),Linux)
HOST_LINUX=-linux
HOST = -DHOST_i386 -DHOST_LINUX
CPP=/lib/cpp
CPPFLAGS = $(INCDIR) -D HOST_i386 -D HOST_LINUX
arch = unknown-i386-linux
ifdef MAKEFILE_TEST
GCCDIR = /usr/local/mips/bin/decstation-ultrix-
LDFLAGS = -T script -N
ASFLAGS = -mips2
endif
endif



arch_dir = arch/$(arch)
obj_dir = $(arch_dir)/objects
bin_dir = $(arch_dir)/bin
depends_dir = $(arch_dir)/depends

endif # MAKEFILE_DEP
